### ISSUE TITLE
Implement PROSPECT-PRO

### ISSUE THREAD

**Issue by jajberni** [jgomezdans/prosail#16]
It would be nice to implement the new version of the PROSPECT model, named PROSPECT-PRO, which separates nitrogen-based constituents (proteins) from CBC (including cellulose, lignin, hemicellulose and starch).

Pre-print: https://arxiv.org/pdf/2003.11961.pdf

Source code in Matlab: https://gitlab.com/jbferet/prospect_pro_matlab

**Comment by jgomezdans** [comment]
Merged & exposed to SAIL.

Many thanks for this

**Comment by dobedobedo** [comment]
Hi,
I have a question about the prospect-pro model. In the original paper of Féret et al (2020), the dry mass is the sum of protein and CBC. However, in the implementation, the dry mass (cm) can be specified separately regardless of prot and cbc values. 
From the original matlab README file (https://gitlab.com/jbferet/prospect_pro_matlab/-/blob/master/README.md), it says this:

> if users want to run PROSPECT-D, CBC and Prot should be set to 0.
> if users want to run PROSPECT-PRO, Cm should be set to 0.

Just want to check if this is still true in the implementation?
